### ISSUE TITLE
Flutter adaptive widgets

### ISSUE THREAD

**Issue by erf** [stryder-dev/flutter_platform_widgets#297]
Not sure you are aware that the following adaptive widgets exists from Flutter:

- Slider.adaptive
- Switch.adaptive (and SwitchListTile.adaptive)
- CircularProgressIndicator.adaptive

Should these still be supported by this library? Are there benefits to using this library vs these adaptive ones? (more configurable perhaps)

**Comment by aqwert** [comment]
Bound to happen over time. When I made this project 3 years ago only Swicth.adaptive existed. There is still value since this project has many more adaptive widgets and a couple of other useful things like switching platforms.

If one wants to use these flutter widgets adaptive style then one can while still using the other widgets from this project

**Comment by erf** [comment]
Thanks. Just like to get your opinion on it :)
