### ISSUE TITLE
PlatformButton

### ISSUE THREAD

**Issue by erperejildo** [stryder-dev/flutter_platform_widgets#354]
What are the options now in Flutter 3 to use a dynamic button as we had before with PlatformButton? I checked the changelog but we no longer have any button option

**Comment by aqwert** [comment]
There is `PlatformElevatedButton` and `PlatformTextButton`

**Comment by erperejildo** [comment]
Before I used to have a `PlatformButton` looking like text on iOS and with an elevated background (material) on Android. That seems to be both both separated. How could I have this now?

**Comment by erperejildo** [comment]
Also why are not these 2 ones appearing in the widgets list?
https://pub.dev/packages/flutter_platform_widgets

**Comment by erperejildo** [comment]
@aqwert what's the solution?

**Comment by aqwert** [comment]
You need to use either `PlatformElevatedButton` or `PlatformTextButton`. These were created since flutter removed the old material buttons. There was a deprecation on `PlatformButton` for a year to give the chance to switch over.

If you want to have a "combined" platform button just create a widget in your project and have a conditional to pick the right button. These new material buttons are so different they needed to have their own separate widget

**Comment by aqwert** [comment]
Another approach I think is to set `originalStyle` to true.

```
PlatformElevatedButton(...,
   cupertino: (_, __) => CupertinoElevatedButtonData(originalStyle: true)
)
```
That will have an "elevated" material button and a "text" cupertino button.

Same can be done for `PlatformTextButton` where it have a "text" material button and a "filled" cupertino button
